### ISSUE TITLE
Switch `TerminateInstances` calls to use `TerminateInstanceInAutoScalingGroup` instead

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/upgrade-manager#18]
In order to support lifecycle hooks, upgrade-manager should not use `ec2:TerminateInstances` calls, and should instead switch to `autoscaling:TerminateInstanceInAutoScalingGroup`, this means lifecycle hooks will be fired before actual termination.

The only change required is to also pass the scaling group name to the call.

In docs it seems AWS access required is already being added to do this, however the calls being made are actually `ec2:TerminateInstances`

https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_TerminateInstanceInAutoScalingGroup.html

**Comment by deepakbenny** [comment]
@eytan-avisror can I work on this?

**Comment by eytan-avisror** [comment]
@deepakbenny Yes, thanks!
This should be pretty straight forward.. looking at the required API call again, it takes the same parameter - instance-id only.

https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#TerminateInstanceInAutoScalingGroupInput

**Comment by shrinandj** [comment]
Fixed with 999848d.
