### ISSUE TITLE
Switch to go modules

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/upgrade-manager#22]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Currently, upgrade-manager uses vendor directories that are populated using `dep ensure`

**What you expected to happen**:
Since several Golang projects are switching to go modules, it might be worth investigating whether upgrade-manager should also switch to go modules. Doing this now, kinda earlier in the projects lifecycle might be easier.

**Comment by johandry** [comment]
I forked the project and open the PR #23.
It was basically all done regarding modules, the only change is basically upgrade to Go 1.13.

If the PR is not merged, I think this issue should be closed.

**Comment by kianjones4** [comment]
closed by #23
