### ISSUE TITLE
drainTimeout command line argument is incorrectly used as a floor rather than a default.

### ISSUE THREAD

**Issue by preflightsiren** [keikoproj/upgrade-manager#304]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report

**What happened**: setting `spec.strategy.drainTimeout` < `900` results in drain timeout  of 900s being set.

**What you expected to happen**: `kubectl drain --timeout=spec.strategy.drainTimeout`

**How to reproduce it (as minimally and precisely as possible)**: using controller-v2 (eg. v1.0.2), creating a `rollingUpgrade` with `drainTimeout` < 900s (the default). If you check the log output you should see that the timeout is set to 900s

**Anything else we need to know?**:

**Environment**:
- rolling-upgrade-controller version v1.0.2

**Comment by shreyas-badiger** [comment]
Fixed. https://github.com/keikoproj/upgrade-manager/pull/307
