### ISSUE TITLE
Ability to control max parallel upgrades

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/upgrade-manager#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
On some big clusters with many different IGs, upgrade-manager can start upgrades of all of them in parallel. This has performance benefits. However, at times, too many parallel upgrades can cause hitting AWS API limits. Or at least it can significantly increase the AWS API rate which can result in other components hitting rate limits.

**What you expected to happen**:
It should be possible to control how many `RollingUpgrade` objects get processed in parallel. This would be a setting at the controller level. Admins can set the correct amount of parallelism depending on which and how many other components exist that can cause AWS API rate limits.

**Comment by eytan-avisror** [comment]
Considering each CR reconciles independently, you need to be able to "pause" processing of new CR changes when you have N reconciling CRs.
Any ideas on how to do that?
