### ISSUE TITLE
Support AWS LaunchTemplates

### ISSUE THREAD

**Issue by uthark** [keikoproj/upgrade-manager#42]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

Upgrade Manager doesn't support LaunchTemplates as of now.
Do you have any plans on adding this feature (btw, kops supports LaunchTemplates)

Would you accept PR that adds support for it?

**Comment by shrinandj** [comment]
> Would you accept PR that adds support for it?

Absolutely!
