### ISSUE TITLE
How to reference the node being drained in the post drain script

### ISSUE THREAD

**Issue by CAR6807** [keikoproj/upgrade-manager#52]
How can the controller reference the node being drain/targeted in the post drain command. Use case is to add additional label/annotations to the targeted node.

**Comment by shrinandj** [comment]
Here's an example of the use of nodename in the scripts: https://github.com/keikoproj/upgrade-manager/blob/master/docs/step-by-step-example.md#create-the-rollingupgrade-custom-resource-cr-that-will-actually-do-the-rolling-upgrade

**Comment by CAR6807** [comment]
Thank you for some reason it didn't work the first time. I was now able to run that example with success

**Comment by shrinandj** [comment]
Fantastic! Let us know if you were able to successfully add label/annotation to the node. If so, could you add some documentation about how to do it? Would be good for others as a reference.
