### ISSUE TITLE
Question: How to detect bad AMI/Configuration and stop the rollout?

### ISSUE THREAD

**Issue by uthark** [keikoproj/upgrade-manager#64]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Question

**What happened**:
If underlying AMI is bad for whatever reason and new instance doesn't join the cluster, what is the best way to detect the issue and stop the rollout?

**Environment**:
- rolling-upgrade-controller version: 0.6.0
- Kubernetes version : 1.16.7

**Comment by eytan-avisror** [comment]
Pretty sure in latest version with eager mode we don't proceed with the rollingUpgrade unless we see all instance inService as joined to cluster

See method: `WaitForDesiredNodes`
https://github.com/keikoproj/upgrade-manager/blob/master/controllers/rollingupgrade_controller.go#L278

Quick workaround would be to use eager mode, we should extend this logic to lazy mode as well

**Comment by uthark** [comment]
Ah, we use eager mode, by the way.

**Comment by eytan-avisror** [comment]
Did you have an instance where the upgrade proceeded even though the nodes did not join? it could be a bug in that case... logs might help in this case

**Comment by uthark** [comment]
Yes, new node started but due to misconfiguration it didn't join the cluster.

I'll try to reproduce again and debug/collect logs.
