### ISSUE TITLE
Autoscaling prevents ASG from rolling update.

### ISSUE THREAD

**Issue by uthark** [keikoproj/upgrade-manager#74]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG

**What happened**:
If ASGs was scaled in during rolling upgrade, upgrade will fail.

**What you expected to happen**:
https://github.com/keikoproj/upgrade-manager/blob/4f02093e60cd739a5966c5de687c368efa08e660/controllers/rollingupgrade_controller.go#L297-L319 - should refresh ASG details.

**How to reproduce it (as minimally and precisely as possible)**:
Start rollout, then manually scale down the ASG.

**Anything else we need to know?**:

**Environment**:
- rolling-upgrade-controller version
- Kubernetes version : 1.16.7

**Other debugging information (if applicable)**:
- RollingUpgrade status:
```
$ kubectl describe rollingupgrade <rollingupgrade-name>
```
- controller logs:
```
$ kubectl logs <rolling-upgrade-controller pod>

upgrade-manager-7c56c9d469-xgf6c rolling-upgrade-controller time="2020-03-10T21:29:24Z" level=info msg="rollingupgrade-node-eu-central-1b: desired capacity is met, 22 instances in service"
upgrade-manager-7c56c9d469-xgf6c rolling-upgrade-controller time="2020-03-10T21:29:24Z" level=info msg="rollingupgrade-node-eu-central-1b: desired capacity is met, 22 instances in service"
upgrade-manager-7c56c9d469-xgf6c rolling-upgrade-controller time="2020-03-10T21:29:24Z" level=info msg="rollingupgrade-node-eu-central-1b: new node has not yet joined the cluster"
...
upgrade-manager-7c56c9d469-xgf6c rolling-upgrade-controller time="2020-03-10T21:39:21Z" level=info msg="rollingupgrade-node-eu-central-1b: new node has not yet joined the cluster"
upgrade-manager-7c56c9d469-xgf6c rolling-upgrade-controller time="2020-03-10T21:39:22Z" level=info msg="Deleted the entries of ASG XXX in the cluster store for rollingupgrade-node-eu-central-1b"
upgrade-manager-7c56c9d469-xgf6c rolling-upgrade-controller time="2020-03-10T21:39:22Z" level=info msg="Marked object rollingupgrade-node-eu-central-1b as error"
```

**Comment by shrinandj** [comment]
Doest the rolling-upgrade crash or does it simply `hang` waiting for the desired nodes to join the cluster?

**Comment by uthark** [comment]
It waits till timeout and then marks rollout as failing.

**Comment by uthark** [comment]
During this 10 min time period actual ASG size was decreased from 22 to 16 (we use autoscale extensively)

**Comment by eytan-avisror** [comment]
This rings a bell :(
<img width="830" alt="Screen Shot 2020-03-10 at 2 52 33 PM" src="https://user-images.githubusercontent.com/20558545/76362747-cf653680-62de-11ea-968c-d3d30da0167a.png">

**Comment by eytan-avisror** [comment]
I think we ended removing it, now I remember why it was needed

**Comment by eytan-avisror** [comment]
However, it should not have been in SetStandby, we need it inside waiters

**Comment by uthark** [comment]
<img width="1200" alt="Screen Shot 2020-03-10 at 2 54 31 PM" src="https://user-images.githubusercontent.com/176118/76362899-2bc85600-62df-11ea-8ea0-eb0a9ec9335d.png">
This is ASG size change during rollout.

**Comment by eytan-avisror** [comment]
This is a bit problematic from throttling perspective, since if you are running 50 ASGs at the same time, you will make this call quite often.

**Comment by shrinandj** [comment]
This is a bit confusing... there is a call to `populateASG` inside `WaitForDesiredInstances` already. So, when do we have a case where the check for desired # of instances is using stale data? Can we post a timeline of events that can result in this bug?

https://github.com/keikoproj/upgrade-manager/blob/4f02093e60cd739a5966c5de687c368efa08e660/controllers/rollingupgrade_controller.go#L267

**Comment by eytan-avisror** [comment]
@shrinandj problem is in `WaitForDesiredInstances` I believe - it relies on what we have in cache via 
https://github.com/keikoproj/upgrade-manager/blob/4f02093e60cd739a5966c5de687c368efa08e660/controllers/rollingupgrade_controller.go#L296-L300

**Comment by eytan-avisror** [comment]
Technically, if we are already doing it in `WaitForDesiredInstances` we already have a potential problem with throttling.
I'm just worried this will be a problem with very large scale (50+ ASG), although using IEB should make it not-as-bad

**Comment by eytan-avisror** [comment]
> @eytan-avisror Yeah, it's cached. Should refresh periodically, probably, not every round.. but once a minute?

It's still a lot of calls if you consider 50 scaling groups in parallel all hitting DescribeAutoScalingGroups API once a minute.

I think it should relatively safe considering we have retries in this case (throttled call), and we are using inverse exponential backoff

**Comment by eytan-avisror** [comment]
Another option is to integrate https://github.com/keikoproj/aws-sdk-go-cache and set a TTL we think is OK

**Comment by shrinandj** [comment]
> @shrinandj problem is in WaitForDesiredNodes I believe - it relies on what we have in cache via

It does *not* use cached data. The call to `populateAsg` queries AWS and updates the object in the map:
```
        asg := result.AutoScalingGroups[0]
        r.ruObjNameToASG.Store(ruObj.Name, asg)
```

And `r.GetAutoScalingGroup` should return the correct object:
```
        val, ok := r.ruObjNameToASG.Load(rollupName)
        if !ok {
                return asg, fmt.Errorf("Unable to load ASG with name: %s", rollupName)
        }
        asg = val.(*autoscaling.Group)
        return asg, nil
```

Is there any subtle bug here?

**Comment by eytan-avisror** [comment]
@shrinandj we dont call populateASG in `WaitForDesiredNodes`

**Comment by eytan-avisror** [comment]
Call is made:
https://github.com/keikoproj/upgrade-manager/blob/4f02093e60cd739a5966c5de687c368efa08e660/controllers/rollingupgrade_controller.go#L263-L286


Call is not made:
https://github.com/keikoproj/upgrade-manager/blob/4f02093e60cd739a5966c5de687c368efa08e660/controllers/rollingupgrade_controller.go#L288-L324

**Comment by shrinandj** [comment]
🤦‍♂ .. Sorry, my bad!

You're right..

If the ASG scales down in between `WaitForDesiredInstances` and `WaitForDesiredNodes` , there is a case where the cached `asg` object is used. This can cause the `WaitForDesiredNodes` call to simply keep waiting and eventually timeout and fail.

```
        // Wait for new instance to be created
        err = r.WaitForDesiredInstances(ruObj)
        if err != nil {
                ch <- err
                return
        }

*** SCALE_DOWN ***
*** SCALE_DOWN ***
*** SCALE_DOWN ***
*** SCALE_DOWN ***

        // Wait for in-service nodes to be ready and match desired
        err = r.WaitForDesiredNodes(ruObj)
        if err != nil {
                ch <- err
                return
        }
```

**Comment by eytan-avisror** [comment]
Lets integrate SDK caching, and add that second call, I can work on it if you want @shrinandj 
LMK
