### ISSUE TITLE
Upgrade-Managers fails to update status of RU until final execution

### ISSUE THREAD

**Issue by CAR6807** [keikoproj/upgrade-manager#91]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug
**What happened**:
Upgrade Manager Fails to Update Status of RollingUpgrade Object, only updated to completed after execution

**What you expected to happen**:
Status should be updated to Running, but only updates to completed once RU is reconciled
**How to reproduce it (as minimally and precisely as possible)**:
Submit a CRD to the Upgrade Manager
**Environment**:
- rolling-upgrade-controller version: 0.10.0
- Kubernetes version : 1.15.9

**Other debugging information (if applicable)**:
- RollingUpgrade status:
Name:         kube-worker-nwm-poc20200430124636975400000020-2020-04-30
Namespace:    kube-system
Labels:       availabilityZone=us-east-1a
Annotations:  janitor/ttl: 1d
API Version:  upgrademgr.keikoproj.io/v1alpha1
Kind:         RollingUpgrade
Metadata:
  Creation Timestamp:  2020-04-30T13:20:24Z
  Generate Name:       kube-worker-nwm-poc20200430124636975400000020-2020-04-30
  Generation:          2
  Resource Version:    460198
  Self Link:           /apis/upgrademgr.keikoproj.io/v1alpha1/namespaces/kube-system/rollingupgrades/kube-worker-nwm-poc20200430124636975400000020-2020-04-30
  UID:                 8bc4277a-8c10-4f93-9815-9fe8e9c01e3c
Spec:
  Asg Name:               kube-worker-nwm-poc20200430124636975400000020
  Node Interval Seconds:  30
  Strategy:
    Drain Timeout:    120
    Max Unavailable:  1
    Mode:             eager
    Type:             randomUpdate
Status:
  Conditions:
    Status:               True
    Type:                 Complete
  Current Status:         completed
  End Time:               2020-04-30T13:24:30Z
  Nodes Processed:        1
  Start Time:             2020-04-30T13:20:25Z
  Total Nodes:            1
  Total Processing Time:  4m5.813454056s
Events:
  Type    Reason                          Age        From             Message
  ----    ------                          ----       ----             -------
  Normal  RollingUpgradeStarted           <unknown>  upgrade-manager  {"asgName":"kube-worker-nwm-poc202004301246369754000000200","msg":"Rolling Upgrade has started","status":"started","strategy":"randomUpdate"}
  Normal  RollingUpgradeInstanceStarted   <unknown>  upgrade-manager  {"asgName":"kube-worker-nwm-poc20200430124636975400000020","msg":"Started Updating Instance i-0864938f568ed8c46, in AZ: us-east-1a","status":"in-progress","strategy":"randomUpdate"}
  Normal  RollingUpgradeFinished          <unknown>  upgrade-manager  {"asgName":"kube-worker-nwm-poc20200430124636975400000020","info":"Rolling Upgrade as finished (status=completed)","status":"completed","strategy":"randomUpdate"}
  Normal  RollingUpgradeInstanceFinished  <unknown>  upgrade-manager  {"asgName":"kube-worker-nwm-poc20200430124636975400000020","msg":"Finished Updating Instance 1/1 (Errors=0)","status":"in-progress","strategy":"randomUpdate"}

- controller logs:
```
$ kubectl logs <rolling-upgrade-controller pod>
```
2020-04-30T13:20:25.120Z	ERROR	controllers.RollingUpgrade	failed to update status	{"rollingupgrade": "kube-worker-nwm-poc20200430124636975400000020-2020-04-30", "error": "the server could not find the requested resource (put rollingupgrades.upgrademgr.keikoproj.io kube-worker-nwm-poc20200430124636975400000020-2020-04-30)"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/keikoproj/upgrade-manager/controllers.(*RollingUpgradeReconciler).error
	/workspace/controllers/rollingupgrade_controller.go:1101
github.com/keikoproj/upgrade-manager/controllers.(*RollingUpgradeReconciler).Process
	/workspace/controllers/rollingupgrade_controller.go:692
github.com/keikoproj/upgrade-manager/controllers.(*RollingUpgradeReconciler).Reconcile
	/workspace/controllers/rollingupgrade_controller.go:766
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88
2020-04-30T13:20:25.120Z	INFO	controllers.RollingUpgrade	Nodes in ASG that *might* need to be updated	{"rollingupgrade": "kube-worker-nwm-poc20200430124636975400000020-2020-04-30", "asgName": "kube-worker-nwm-poc20200430124636975400000020", "asgSize": 1}
2020/04/30 13:20:25 Max unavailable calculated for kube-worker-nwm-poc20200430124636975400000020-2020-04-30 is 1
2020-04-30T13:20:25.163Z	INFO	controllers.RollingUpgrade	selected instances for rotation: [{
  AvailabilityZone: "us-east-1a",
  HealthStatus: "Healthy",
  InstanceId: "i-0864932348f568ed8c46",
  LaunchTemplate: {
    LaunchTemplateId: "lt-00cd32cb6da6d419bc1",
    LaunchTemplateName: "kube-worker-nwm-poc20200430124636975400000020",
    Version: "1"
  },
  LifecycleState: "InService",
  ProtectedFromScaleIn: false
}]
```

**Comment by eytan-avisror** [comment]
Yeah, we've seen failures to update status as well but due to a conflict (after the CR changes once we need to re-fetch the rollup object - we will fix this soon), I don't think we've seen the error you are getting of:
```
the server could not find the requested resource
```
Are you getting this error consistently for every RU you submit?

**Comment by CAR6807** [comment]
@eytan-avisror I've got this error when I went from v0.6 v0.10, with every RU submitted. The RU successfully is created and runs, but the expected status of running does not appears, and the above error seems to be the cause. But if `kubectl get ru name` listed in the error, the RU does exist and is correctly spelled. Are there api versions change between v0.6 and v0.10 from RU perspective.

**Comment by eytan-avisror** [comment]
@CAR6807 
There are CRD changes + RBAC changes required.

Make sure the following is up to date:
- CRD: https://github.com/keikoproj/upgrade-manager/blob/master/config/crd/bases/upgrademgr.keikoproj.io_rollingupgrades.yaml
- RBAC: https://github.com/keikoproj/upgrade-manager/blob/master/config/rbac/role.yaml
- CR `.spec.region` has been deprecated - remove if/any from your spec

It's probably since we added RBAC for
```
  resources:
  - rollingupgrades/status
  verbs:
  - get
  - patch
  - update
```
And the controller doesn't have this access. I think once you update both it should work.
We still have issues around updating status, but it shouldn't be consistently failing.

**Comment by CAR6807** [comment]
I updated the CRDs and that seems to resolve the issue, status are properly being updated and reported. I'll keep testing out the v10 with our existing automation, but I think it looks good. 
Thanks for the quick response and help
